#376: removed wrapper function for echo usage

diff --git a/start b/start
--- a/start
+++ b/start
@@ -24,9 +24,9 @@ QUICKSTART_INITIALIZED=false
 CURRENT_POSTGRES_PID=""
 
 function main() {
-  print_screen_output "" 
-  print_screen_output "Starting Stellar Quickstart"
-  print_screen_output ""
+  echo "" 
+  echo "Starting Stellar Quickstart"
+  echo ""
 
   process_args $*
   if [ "$NETWORK" != "standalone" ] && [ "$ENABLE_HORIZON_CAPTIVE_CORE" = "true" ]; then
@@ -50,8 +50,8 @@ function main() {
     exit 1
   fi
 
-  print_screen_output "mode: $STELLAR_MODE"
-  print_screen_output "network: $NETWORK ($NETWORK_PASSPHRASE)"
+  echo "mode: $STELLAR_MODE"
+  echo "network: $NETWORK ($NETWORK_PASSPHRASE)"
 
   copy_defaults
   init_db
@@ -108,7 +108,7 @@ function process_args() {
       RANDOMIZE_NETWORK_PASSPHRASE=true
       ;;
     *)
-      print_screen_output "Unknown container arg $ARG" >&2
+      echo "Unknown container arg $ARG" >&2
       exit 1
     esac
   done
@@ -137,7 +137,7 @@ function process_args() {
     export HISTORY_ARCHIVE_URLS="http://history-futurenet.stellar.org"
     ;;  
   *)
-    print_screen_output "Unknown network: '$NETWORK'" >&2
+    echo "Unknown network: '$NETWORK'" >&2
     exit 1
   esac
 
@@ -159,19 +159,19 @@ function set_pg_password() {
 
   if [ -n "$POSTGRES_PASSWORD" ]; then
     PGPASS=$POSTGRES_PASSWORD
-    print_screen_output "using POSTGRES_PASSWORD"
+    echo "using POSTGRES_PASSWORD"
     return 0
   fi
 
   # use a random password when ephemeral (or some other unknown mode)
   if [ "$STELLAR_MODE" != "persistent" ]; then
     PGPASS=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' |  head -c 16)
-    print_screen_output "postgres password: $PGPASS"
+    echo "postgres password: $PGPASS"
     return 0
   fi
 
   if [ -n "$PGPASS" ]; then
-    print_screen_output "postgres password: $PGPASS"
+    echo "postgres password: $PGPASS"
     return 0
   fi
 
@@ -182,12 +182,12 @@ function set_pg_password() {
   echo ""
 
   if [ -z "$PGPASS" ]; then
-    print_screen_output "Password empty" >&2
+    echo "Password empty" >&2
     exit 1
   fi
 
   if [ "$PGPASS" != "$PGPASS_CONFIRMATION" ]; then
-    print_screen_output "Password mistmach" >&2
+    echo "Password mistmach" >&2
     exit 1
   fi
 
@@ -197,13 +197,13 @@ function copy_defaults() {
   local CP="rsync -a"
 
   if [ -d $PGHOME/etc ]; then
-    print_screen_output "postgres: config directory exists, skipping copy"
+    echo "postgres: config directory exists, skipping copy"
   else
     $CP /opt/stellar-default/common/postgresql/ $PGHOME
   fi
 
   if [ -d $SUPHOME/etc ]; then
-    print_screen_output "supervisor: config directory exists, skipping copy"
+    echo "supervisor: config directory exists, skipping copy"
   else
     $CP /opt/stellar-default/common/supervisor/ $SUPHOME
     if [ "$ENABLE_SOROBAN_RPC" = "true" ]; then
@@ -213,20 +213,20 @@ function copy_defaults() {
   fi
 
   if [ -d $COREHOME/etc ]; then
-    print_screen_output "stellar-core: config directory exists, skipping copy"
+    echo "stellar-core: config directory exists, skipping copy"
   else
     $CP /opt/stellar-default/common/core/ $COREHOME
     $CP /opt/stellar-default/$NETWORK/core/ $COREHOME
   fi
 
   if [ -d $HZHOME/etc ]; then
-    print_screen_output "horizon: config directory exists, skipping copy"
+    echo "horizon: config directory exists, skipping copy"
   else
     $CP /opt/stellar-default/common/horizon/ $HZHOME
   fi
 
   if [ -d $SOROBAN_RPC_HOME/etc ]; then
-    print_screen_output "soroban-rpc: config directory exists, skipping copy"
+    echo "soroban-rpc: config directory exists, skipping copy"
   else
     $CP /opt/stellar-default/common/soroban-rpc/ $SOROBAN_RPC_HOME
     if [ -d /opt/stellar-default/$NETWORK/soroban-rpc/ ]; then
@@ -235,7 +235,7 @@ function copy_defaults() {
   fi
 
   if [ -d $FBHOME/etc ]; then
-    print_screen_output "friendbot: config directory exists, skipping copy"
+    echo "friendbot: config directory exists, skipping copy"
   else
     $CP /opt/stellar-default/common/friendbot/ $FBHOME
     if [ -d /opt/stellar-default/$NETWORK/friendbot/ ]; then
@@ -244,7 +244,7 @@ function copy_defaults() {
   fi
 
   if [ -d $NXHOME/etc ]; then
-    print_screen_output "nginx: config directory exists, skipping copy"
+    echo "nginx: config directory exists, skipping copy"
   else
     $CP /opt/stellar-default/common/nginx/ $NXHOME
     if [ -d /opt/stellar-default/$NETWORK/nginx/ ]; then
@@ -266,7 +266,7 @@ function copy_pgpass() {
 
 function init_db() {
   if [ -f $PGHOME/.quickstart-initialized ]; then
-    print_screen_output "postgres: already initialized"
+    echo "postgres: already initialized"
     return 0
   fi
   pushd $PGHOME
@@ -275,7 +275,7 @@ function init_db() {
   mkdir /etc/ssl/private-copy; mv /etc/ssl/private/* /etc/ssl/private-copy/; rm -r /etc/ssl/private; mv /etc/ssl/private-copy /etc/ssl/private; chmod -R 0700 /etc/ssl/private; chown -R postgres /etc/ssl/private
   # end workaround
 
-  print_screen_output "postgres user: $PGUSER"
+  echo "postgres user: $PGUSER"
 
   set_pg_password
 
@@ -310,7 +310,7 @@ function init_stellar_core() {
   pushd $COREHOME
   run_silent "chown-core" chown -R stellar:stellar .
   if [ -f $COREHOME/.quickstart-initialized ]; then
-    print_screen_output "core: already initialized"
+    echo "core: already initialized"
 
     if [ "$NETWORK" == "standalone" ]; then
       start_postgres
@@ -355,7 +355,7 @@ function init_stellar_core() {
 
 function init_horizon() {
   if [ -f $HZHOME/.quickstart-initialized ]; then
-    print_screen_output "horizon: already initialized"
+    echo "horizon: already initialized"
     return 0
   fi
   pushd $HZHOME
@@ -399,7 +399,7 @@ function init_soroban_rpc() {
   fi   
 
   if [ -f $SOROBAN_RPC_HOME/.quickstart-initialized ]; then
-    print_screen_output "soroban rpc: already initialized"
+    echo "soroban rpc: already initialized"
     return 0
   fi
   pushd $SOROBAN_RPC_HOME
@@ -432,7 +432,7 @@ function upgrade_standalone() {
 }
 
 function exec_supervisor() {
-  print_screen_output "starting supervisor..."
+  echo "starting supervisor..."
   upgrade_standalone &
   service_status &
   exec supervisord -n -c $SUPHOME/etc/supervisord.conf
@@ -453,12 +453,12 @@ function run_silent() {
   $COMMAND $ARGS &> $OUTFILE
 
   if [ $? -eq 0 ]; then
-    print_screen_output "$LABEL: ok"
+    echo "$LABEL: ok"
   else
-    print_screen_output "$LABEL: failed!"
-    print_screen_output ""
+    echo "$LABEL: failed!"
+    echo ""
     DUMPOUT=$(cat $OUTFILE)
-    print_screen_output "$DUMPOUT"
+    echo "$DUMPOUT"
     exit 1
   fi
 
@@ -474,11 +474,11 @@ function start_postgres() {
   CURRENT_POSTGRES_PID=$!
 
   while ! sudo -u postgres psql -c 'select 1' &> /dev/null ; do
-    print_screen_output "Waiting for postgres to be available..."
+    echo "Waiting for postgres to be available..."
     sleep 1
   done
 
-  print_screen_output "postgres: up"
+  echo "postgres: up"
 }
 
 function stop_postgres() {
@@ -491,7 +491,7 @@ function stop_postgres() {
   while kill -0 "$CURRENT_POSTGRES_PID" &> /dev/null; do
     sleep 0.5
   done
-  print_screen_output "postgres: down"
+  echo "postgres: down"
 }
 
 pushd () {
@@ -510,7 +510,7 @@ function service_status () {
 }
 
 function soroban_rpc_status () { 
-  print_screen_output "soroban rpc: waiting for ready state..."
+  echo "soroban rpc: waiting for ready state..."
   COUNTER=1
   while ! $(curl --silent --location --request POST 'http://localhost:8000/soroban/rpc' \
     --header 'Content-Type: application/json' \
@@ -522,32 +522,28 @@ function soroban_rpc_status () {
     }' | jq --exit-status '.result.status == "healthy"' 2>/dev/null | grep -o true || echo false ); 
   do
     if [ $(expr $COUNTER % 12) -eq 0 ]; then 
-      print_screen_output "soroban rpc: waiting for ready state, $(expr $COUNTER / 12) minutes..."
+      echo "soroban rpc: waiting for ready state, $(expr $COUNTER / 12) minutes..."
     fi 
     COUNTER=$[$COUNTER +1]
     sleep 5
   done 
-  print_screen_output "soroban rpc: up and ready"
+  echo "soroban rpc: up and ready"
 }
 
 function horizon_status () {
   COUNTER=1
-  print_screen_output "horizon: waiting for ingestion to catch up..."
+  echo "horizon: waiting for ingestion to catch up..."
   while ! $(curl --silent --location --request GET 'http://localhost:8000' | \
     jq --exit-status '.core_latest_ledger > 5 and .history_latest_ledger > 5' 2>/dev/null | \
     grep -o true || echo false ); 
   do
     if [ $(expr $COUNTER % 12) -eq 0 ]; then 
-      print_screen_output "horizon: waiting for ingestion to catch up, $(expr $COUNTER / 12) minutes..."
+      echo "horizon: waiting for ingestion to catch up, $(expr $COUNTER / 12) minutes..."
     fi 
     COUNTER=$[$COUNTER +1]
     sleep 5
   done 
-  print_screen_output "horizon: ingestion caught up"
-}
-
-function print_screen_output() {
-  echo "$1" 
+  echo "horizon: ingestion caught up"
 }
 
 main $@
